# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: ubuntu-latest

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'
  
Settings:
- task: UsePythonVersion@0
      inputs:
        versionSpec: '3.8'
      displayName: 'Install Python 3.8'
    - script: pip install checkov
      displayName: 'Install Checkov'
    - script: checkov -d . --use-enforcement-rules --bc-api-key 8885d84f-9f12-40c5-96f2-74a112594202::GY494u6yPwHZWpDi2IxVUTivjoc= --repo-id FaCezar/terragoat --branch main
      displayName: 'Scan with Prisma Cloud'
      env:
        PRISMA_API_URL: <https://api.prismacloud.io>  

