# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pr:
- main

pool:
  vmImage: ubuntu-latest

variables:
  PRISMA_API_URL: https://api.prismacloud.io

jobs:
- job: Prisma_Cloud_Job
  displayName: Prisma Cloud Job
  steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: '3.8'
  displayName: 'Install Python 3.8'
- script: pip install checkov
  displayName: 'Install Checkov'
- script: checkov -d  . --use-enforcement-rules --bc-api-key 8885d84f-9f12-40c5-96f2-74a112594202::GY494u6yPwHZWpDi2IxVUTivjoc= --repo-id FaCezar/terragoat --branch <branch>
  displayName: 'Scan with Prisma Cloud'
  env:
    PRISMA_API_URL: https://api.prismacloud.io
